sonar.projectKey=ManuelRisco_PIZZA_HUT_MVP_Frontend
sonar.projectName=Pizza Hut MVP - Frontend
sonar.sources=src
sonar.host.url=http://localhost:9000

sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/pizzahut/lcov.info
sonar.javascript.lcov.reportPaths=coverage/pizzahut/lcov.info
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
