version: '3.8'

services:
  backend:
    build:
      context: ./Backend/demo
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    env_file:
      - ./Backend/demo/.env
    # depends_on: 
    #   - db # Descomentar si decides agregar una BD local en el futuro

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
